# Generated by Django 4.2.5 on 2023-09-06 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_alter_curso_nivel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='nivel',
            field=models.CharField(choices=[(0, 'Iniciante'), (1, 'Intermediário'), (2, 'Avançado')], max_length=50),
        ),
    ]
